import Head from 'next/head';
import IframeList from '~/components/IframeList';

const list = [
  {
    url: 'https://www.youtube.com/embed/1Mi-_Plz5as?si=qUI-ZiHkK9PE0IEG',
    memo: 'アクセシビリティカンファレンス福岡の会場で放映されてたマーカッポの動画\n会場で大ウケだった\nマークアップに携わる人なら誰でも楽しめる内容',
  },
  {
    url: 'https://www.youtube.com/embed/qq9R7-1FptQ?si=Y3GBJHltOghp44fp',
    memo: 'マーカッポの1回目の動画\n面白い',
  },
  {
    url: 'https://www.youtube.com/embed/2H49N5e7hPw?si=JIFi6VrwUkMIqZFi',
    memo: 'マーカッポ#2の振り返り動画\nマーカッポが勉強になるとつぶやいたのを拾ってもらえて、まじめに受け取るなと言われてしまいました',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Next Swipe Iframe Sample</h1>
        <p>iframeをスワイプして次のiframeに表示を切り換えるサンプル</p>
        <p>以下のページを参考にした</p>
        <p>
          <a href="https://react-spectrum.adobe.com/react-aria/examples/swipeable-tabs.html">
            https://react-spectrum.adobe.com/react-aria/examples/swipeable-tabs.html
          </a>
        </p>
        <p>ああああ</p>
        <p>ああああ</p>
        <p>ああああ</p>
        <IframeList list={list} defaultIndex={1} />
      </main>
    </>
  );
}
