import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Next Swipe Iframe Sample</h1>
        <p>iframeをスワイプして次のiframeに表示を切り換えるサンプル</p>
        <p>以下のページを参考にした</p>
        <p>
          <a href="https://react-spectrum.adobe.com/react-aria/examples/swipeable-tabs.html">
            https://react-spectrum.adobe.com/react-aria/examples/swipeable-tabs.html
          </a>
        </p>
      </main>
    </>
  );
}
